- name: Set password on User debian
  ansible.builtin.user:
    name: debian
    password: "$y$j9T$z5kEdppfL2Iie0nI.MK/c0$ZLkX5b3a2BKKhBF/MtiH1yW.5iIzrc4wClOwr3tWBD."
    update_password: always
  become: yes
    
- name: Update apt repo cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Update all packages
  apt:
    upgrade: dist
    autoremove: yes
  become: yes
